/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author The_Fusy
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <algorithm>
#include <string>
#include <vector>
#include <map>
#include <set>
#include <cmath>

#define X first
#define Y second

using namespace std;

typedef long long ll;
typedef long double ld;

class TaskA {
public:
	void solve(istream &cin, ostream &cout) {
        ll n;
        cin>>n;
        char v[101][101];
        for(ll i=0;i<n;i++){
            for(ll j=0;j<n;j++){
                v[i][j]='*';
            }
        }
        for(ll i=0;i<n/2;i++){
            for(ll j=0;j<=i;j++){
                v[i][n/2+j]='D';
                v[i][n/2-j]='D';
                v[n-i-1][n/2+j]='D';
                v[n-i-1][n/2-j]='D';
            }
        }
        for(ll i=0;i<n;i++){
            for(ll j=0;j<n;j++){
                if(i!=n/2) cout<<v[i][j];
                else cout<<"D";
            }
            cout<<endl;
        }
	}
};


int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(0);
	TaskA solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}