/**

 * code generated by JHelper

 * More info: https://github.com/AlexeyDmitriev/JHelper

 * @author

 */



// Actual solution is at the bottom



#undef NDEBUG



#include <algorithm>

#include <array>

#include <bitset>

#include <cassert>

#include <climits>

#include <cstdint>

#include <cmath>

#include <complex>

#include <cstdio>

#include <cstdlib>

#include <cstring>

#include <functional>

#include <iomanip>

#include <iostream>

#include <map>

#include <memory>

#include <numeric>

#include <queue>

#include <random>

#include <set>

#include <stack>

#include <string>

#include <unordered_set>

#include <unordered_map>

#include <vector>

#include <fstream>

// AtCoder library from https://github.com/atcoder/ac-library

// #include "../atcoder/all"



#define sz(v) ((int)(v).size())

#define all(v) (v).begin(),(v).end()



using namespace std;



using int64 = int64_t;

using ii = pair<int, int>;



class D2IgraVDevyatkuII {

 public:

  int eval(vector<int> hands) {

    array<signed char, 2 * 25 * 25 * 25 * 25> score;

    array<int, 4> nextLeft;

    array<int, 4> nextRight;

    array<int, 4> curs;

    array<int, 4> p25;

    p25[0] = 1;

    for (int i = 1; i < 4; ++i) p25[i] = 25 * p25[i - 1];

    bool prevNoMove;

    for (int state = score.size() - 1; state >= 0; --state) {

      int who = state % 2;

      int rem = state / 2;

      int remaining = 36;

      for (int i = 0; i < 4; ++i) {

        int cur = rem % 25;

        curs[i] = cur;

        rem /= 25;

        if (cur == 0) {

          nextLeft[i] = nextRight[i] = 3;

        } else {

          --cur;

          nextLeft[i] = 2 - cur % 4;

          nextRight[i] = 4 + cur / 4;

        }

        remaining -= max(0, nextRight[i] - nextLeft[i] - 1);

      }

      int cards = 0;

      bool anyMove = false;

      if (who == 0) {

        score[state] = -100;

      } else {

        score[state] = 100;

      }

      for (int i = who * 18; i < (who + 1) * 18; ++i) {

        int value = hands[i] / 4;

        int suit = hands[i] % 4;

        if (value <= nextLeft[suit] || value >= nextRight[suit]) {

          ++cards;

          if (value == nextLeft[suit] || value == nextRight[suit]) {

            anyMove = true;

            int nl = nextLeft[suit];

            int nr = nextRight[suit];

            if (nl == value) --nl;

            if (nr == value) ++nr;

            int ncur = (nr - 4) * 4 + (2 - nl) + 1;

            int ns = 1 ^(state + 2 * (ncur - curs[suit]) * p25[suit]);

            assert(ns > state);

            signed char got = score[ns];

            if (who == 0) {

              score[state] = max(score[state], got);

            } else {

              score[state] = min(score[state], got);

            }

          }

        }

      }

      if (cards == 0) {

        if (who == 0) {

          score[state] = remaining;

        } else {

          score[state] = -remaining;

        }

      } else if (cards == remaining) {

        if (who == 0) {

          score[state] = -remaining;

        } else {

          score[state] = remaining;

        }

      } else {

        if (prevNoMove) {

          assert(anyMove);

          assert(state % 2 == 0);

          score[state + 1] = score[state];

        }

      }

      prevNoMove = false;

      if (cards > 0 && cards < remaining) {

        if (!anyMove) {

          if (state % 2 == 0) {

            score[state] = score[state + 1];

          } else {

            prevNoMove = true;

          }

        }

      }

    }

    return score[0] - score[1];

  }



  string answer = "6S 6C 9S AC JC KS 7H 6D TH KD AH JH AS 8S JS QC 8C QD \n"

                  "KC 7C 9C 7S 9H 8D QS JD 9D 7D 6H AD QH KH TC TD 8H TS \n"

                  "\n"

                  "6C 7C 8C 9S TC JC QC QH AC 6D AH 8D 9H TD JD AS KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS QD 6H 7H KC 9D TH JH 8H KH 7D \n"

                  "\n"

                  "6C 7C 8C 9S TC JC KS QH AC 6D AH 8D 9H TD JD AS KD AD \n"

                  "6S 7S 8S 9C TS JS QS QC QD 6H 7H KC 9D TH JH 8H KH 7D \n"

                  "\n"

                  "6C 7C 8C 9D TC JC 8S KC AC 6D AH 8D 9H TD JD QD KD AD \n"

                  "6S 7S QC 9C TS JS QS KS AS 6H 7H 8H 9S TH JH QH KH 7D \n"

                  "\n"

                  "6C 7C 8C 9S TC JC QC 8H AC 6D AH 8D 9H TD JD AS KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS QD 6H 7H KC 9D TH JH QH KH 7D \n"

                  "\n"

                  "JD 6C TH QS 7C 9C 7S 6H TS QC AD 9S KH QD 8C AH 9H 8S \n"

                  "QH TC AS AC 6S KC 8D TD 9D KD 7H JC JS 6D 8H KS JH 7D \n"

                  "\n"

                  "6C 7C 8C 9S TC JC 8S KC AC 8H AH KS 9H TD JD QD KD AD \n"

                  "6S 7S QC 9C TS JS QS 8D AS 6H 7H 6D 9D TH JH QH KH 7D \n"

                  "\n"

                  "6C 7C 8C 9S TC JC 8S KC AC 6D AH KS 9H TD JD QD KD AD \n"

                  "6S 7S QC 9C TS JS QS 8D AS 6H 7H 8H 9D TH JH QH KH 7D \n"

                  "\n"

                  "6C 7C 8C 9S TC JC 8S KC AC 6D AH 8D 9H TD JD QD KD AD \n"

                  "6S 7S QC 9C TS JS QS KS AS 6H 7H 8H 9D TH JH QH KH 7D \n"

                  "\n"

                  "6C 7C 8C 9S TC JC QC 8H AC 6D 8S 8D 9H TD JD AS KD AD \n"

                  "6S 7S AH 9C TS JS QS KS QD 6H 7H KC 9D TH JH QH KH 7D \n"

                  "\n"

                  "6C 7C 8C 9S TC JC QC 8H AC 6D AH 8D 9H TD JD QD KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS AS 6H 7H KC 9D TH JH QH KH 7D \n"

                  "\n"

                  "7S 8D 9H QC 7D 8C 6D QD 8H AS 9S 6S AC JS AD 6C KD QS \n"

                  "TC KS 7H 9D 9C JD KC JH AH JC TS KH QH 8S TD 7C TH 6H \n"

                  "\n"

                  "6C 7C 8C 9S TC JC QC 8H AH 6D 8D 7D 9H TD JD QD KD KH \n"

                  "6S 7S 8S 9C TS JS QS KS AS 6H 7H KC 9D TH JH QH AD AC \n"

                  "\n"

                  "KH AS 8C 9S TC JC QC 8H AH 6D 8D 7D 9H TD JD QD KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS 7C 6H 7H KC 9D TH JH QH 6C AC \n"

                  "\n"

                  "6C 7C 8C 9S TC JC QC 8H AC 6D 8D 7D 9H TD 7H QD KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS AS 6H JD KC 9D TH JH QH KH AH \n"

                  "\n"

                  "6C 7C 8C 9S TC JC QC 8H AC 6D AH 7D 9H TD JD QD KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS AS 6H 7H KC 9D TH JH QH KH 8D \n"

                  "\n"

                  "6C 7C 8C 9S TC JC QC KC AC 6D AH 8D 9H TD JD QD KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS AS 6H 7H 8H 9D TH JH QH KH 7D \n"

                  "\n"

                  "6C 7C 8C 9S TC JC AS KC AC 6D 7D 8D 9H TD JD QD KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS QC 6H 7H 8H 9D TH JH QH KH AH \n"

                  "\n"

                  "6C 7C 8C 9S TC JC QC 8H AH 6D 8D 7D 9H TD JD QD KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS AS 6H 7H KC 9D TH JH QH KH AC \n"

                  "\n"

                  "KH 7C 8C 9S TC JC QC 8H AH 6D 8D 7D 9H TD JD QD KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS AS 6H 7H KC 9D TH JH QH 6C AC \n"

                  "\n"

                  "6C 7C TS 9S TC JC QC KC AC 6D 7D QS 9H TD JD QD KD AD \n"

                  "6S 7S 8S 9C 8C JS 8D KS AS 6H 7H 8H 9D TH JH QH KH AH \n"

                  "\n"

                  "6C 7C 8C 9S TC JC QC 8H AC 6D 8D 7D 9H TD JD QD KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS AS 6H 7H KC 9D TH JH QH KH AH \n"

                  "\n"

                  "6C 7C 8C 9S TC JC QC KC AC 6D 7D QS 9H TD JD QD KD AD \n"

                  "6S 7S 8S 9C TS JS 8D KS AS 6H 7H 8H 9D TH JH QH KH AH \n"

                  "\n"

                  "6C 7C 8C 9S TC KC QC 8H QD 6D 8D 7D 9H TD JD AC KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS AS 6H 7H JC 9D TH JH QH KH AH \n"

                  "\n"

                  "6C 7C 8C 9S TC KC QC 8H QD 6D JC 7D 9H TD JD AC KD AD \n"

                  "6S 7S 8S JS TS 9C QS KS AS 6H 7H 8D 9D TH JH QH KH AH \n"

                  "\n"

                  "6C 7C 8C 9S TC JC QC KC AC 6D 7D 8D 9H TD JD QD KD AD \n"

                  "6S 7S 8S 9C TS JS QS KS AS 6H 7H 8H 9D TH JH QH KH AH \n"

                  "\n";



  void solveOne() {

    string suits = "CDSH";

    string values = "6789TJQKA";

    int need;

    cin >> need;

    /*vector<int> hands(36);

    iota(all(hands), 0);

    map<int, vector<int>> sofar;

    mt19937 rng(57);

    map<int, int> tries;

    while (sofar.size() < need) {

      int tr;

      int bs = -1;

      if (sofar.empty()) {

        tr = -2;

        for (int i = 0; i < 4; ++i) {

          for (int j = 0; j < 9; ++j) {

            if (j == 3) {

              hands[i * 9 + j] = j * 4 + (i ^ 2);

            } else {

              hands[i * 9 + j] = j * 4 + i;

            }

          }

        }

      } else if (uniform_int_distribution<int>(0, 10)(rng) == 0) {

        shuffle(all(hands), rng);

        tr = -1;

      } else {

        int ptr = uniform_int_distribution<int>(0, sofar.size() - 1)(rng);

        for (auto [s, v] : sofar) {

          --ptr;

          if (ptr < 0) {

            tr = ++tries[s];

            bs = s;

            hands = v;

            break;

          }

        }

        int swaps = uniform_int_distribution<int>(1, tr / 20 + 1)(rng);

        for (int sw = 0; sw < swaps; ++sw) {

          int i = uniform_int_distribution<int>(0, 35)(rng);

          int j = uniform_int_distribution<int>(0, 35)(rng);

          swap(hands[i], hands[j]);

        }

      }

      int got = abs(eval(hands));

      if (sofar.find(got) == sofar.end()) {

        sofar[got] = hands;

        cerr << sofar.size() << " " << got << " " << tr << " " << bs << endl;

      }

    }

    ofstream output("res.txt");

    for (auto [s, v] : sofar) {

      for (int i = 0; i < 36; ++i) {

        cerr << values[v[i] / 4] << suits[v[i] % 4] << " ";

        output << values[v[i] / 4] << suits[v[i] % 4] << " ";

        if (i % 18 == 17) {

          cerr << "\n";

          output << "\n";

        }

      }

      cerr << "\n";

      output << "\n";

      output.flush();

    }*/

    need *= 3;

    for (char c : answer) {

      cout << c;

      if (c == '\n') {

        --need;

        if (need == 0) break;

      }

    }

  }



  void solve() {

    int nt = 1;

    for (int it = 0; it < nt; ++it) {

      //cout << "Case #" << (it + 1) << ": ";

      solveOne();

      //cerr << "Case #" << (it + 1) << " done" << endl;

    }

  }

};



//#define st_mtimespec st_mtim



int main() {

    std::ios::sync_with_stdio(false);

    std::cin.tie(0);

    D2IgraVDevyatkuII solver;





    solver.solve();

    return 0;

}