/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

//
// Created by Lukas Huwald on 22.05.18.
//

#ifndef PRELUDE_H
#define PRELUDE_H

#define M_PI 3.14159265358979323846
#define EPS 1e-9

#include <algorithm>
#include <cmath>
#include <numeric>

#include <vector>
#include <set>
#include <map>
#include <queue>

#include <iostream>
#include <iomanip>
#include <string>
#include <sstream>

typedef long long ll;
typedef long double ld;

typedef std::pair<int, int> ii;
typedef std::pair<double, double> dd;

typedef std::vector<int> vi;
typedef std::vector<ii> vii;
typedef std::vector<vi> vvi;
typedef std::vector<vii> vvii;

typedef std::vector<char> vc;
typedef std::vector<std::vector<char>> vvc;

typedef std::vector<ll> vll;
typedef std::vector<vll> vvll;
typedef std::vector<double> vd;
typedef std::vector<dd> vdd;

typedef std::string ss;
typedef std::vector<ss> vss;

typedef std::vector<std::pair<int, ii>> EdgeList;

#define REP(i,n) for(int i=0;i<n;++i)
#define FOREACH(it,a) for(auto it=a.begin(); it != a.end(); ++it)

#endif //PRELUDE_H

//
// Created by Lukas Huwald on 22.05.18.
//

#ifndef UNIONFIND_H
#define UNIONFIND_H



class UnionFind {
private:
    vi parent, rank, sizes;
    int count;
public:
    UnionFind(int n) {
        rank.assign(n, 0);
        parent.assign(n, 0);
        sizes.assign(n, 1);
        count = n;
        REP(i, n) {
            parent[i] = i;
        }
    }

    int find(int i) {
        return (parent[i] == i ? i : parent[i] = find(parent[i]));
    }

    void unite(int i, int j) {
        int pi = find(i);
        int pj = find(j);
        if (pi != pj) {
            count--;
            if (rank[pi] > rank[pj]) {
                parent[pj] = pi;
                sizes[pi] = sizes[pj] + sizes[pi];
            }
            else {
                parent[pi] = pj;
                sizes[pj] = sizes[pi] + sizes[pj];
                if (rank[pi] == rank[pj]) {
                    rank[pj]++;
                }
            }
        }
    }

    int numberOfSets() {
        return count;
    }

    int sizeOfSet(int i) {
        return sizes[find(i)];
    }

};

#endif //UNIONFIND_H

class TaskD {
public:
    int n;
    vvi possible;
    vi a;
    int memo[700][700][2];
    void solve(std::istream& in, std::ostream& out) {
        in >> n;
        a = vi(n);
        UnionFind uf(n);

        REP(i, n) {
            in >> a[i];
        }
        possible = vvi(n, vi(n, 0));
        REP(i, n) {
            for (int j = i; j < n; ++j) {
                possible[i][j] = possible[j][i] = (gcd(a[i], a[j]) > 1 ? 1 : 0);
                if (possible[i][j]) {
                    uf.unite(i, j);
                }
            }
        }
        if (uf.numberOfSets() != 1) {
            out << "No";
            return;
        }
        REP(i, n) {
            REP(j, n) {
                REP(k, 2) {
                    memo[i][j][k] = -1;
                }
            }
        }

        for (int root = 0; root < n; ++root) {
            bool res = tryout(0, root-1, 0) && tryout(root+1, n-1, 1);
            if (res) { out << "Yes"; return; }
        }
        out << "No";
    }

    bool tryout(int left, int right, int rootLeft) {
        int root = (rootLeft ? left-1 : right+1);
        if (left > right) { return true; }
        else if (left == right) { return possible[left][root] == 1; }
        else {
            if (memo[left][right][rootLeft] != -1) { return memo[left][right][rootLeft] == 1; }
            for (int subroot = left; subroot <= right; subroot++) {
                if (possible[subroot][root] == 0) { continue; }
                bool subres = tryout(left, subroot-1, 0) && tryout(subroot+1, right, 1);
                if (subres) {
                    memo[left][right][rootLeft] = 1;
                    return true;
                }
            }
            memo[left][right][rootLeft] = 0;
            return false;
        }
    }

    int gcd(int a, int b) {
        if (b == 0) { return a; }
        return gcd(b, a % b);
    }
};


int main() {
	std::ios_base::sync_with_stdio(false);
	std::cin.tie(NULL);
	std::cout << std::fixed;
	std::cout << std::setprecision(15);

	TaskD solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}